### ISSUE TITLE
0.0.8 broke the mod

### ISSUE THREAD

**Issue by girinf** [randomuserhi/KillIndicatorFix#1]
Worked fine on 0.0.7.
0.0.8 seems to make it worse than how it is in the base game.
Didn't know where else to report this so here I am.

**Comment by randomuserhi** [comment]
Could you clarify what you mean by worse?

I assume ur running as a client. 

Are the hit markers not showing up for some enemies? what was ur ping like etc...

ALSO: There is a dev feedback thread on the GTFO modding discord server

**Comment by randomuserhi** [comment]
I did some testing, and I think I found the issue. Feel free to close this issue if you deem it to be fixed.

**Comment by girinf** [comment]
It was presenting orange hitmarkers when the mob definitely was not dead. It did this consistently, as well as not fixing the issue itself either. I'll know soon enough if it's fixed and close the issue if it's fine after then.
